### ISSUE TITLE
Any wonderful badges, Ionică?

### ISSUE THREAD

**Issue by aleen42** [aleen42/badges#1]
Dears,

Hi, @IonicaBizau, I have created a repo for storing a collection of personal badges, which can be reused in different projects. Have you ever seen some awesome badges before? I'm sincerely invited you to contribute for me, and the repo.

Of course, if you want to create some new one, you can use the [**tool**](http://shields.io/#your-badge) powered by Shields. Thank you!

Sincerely yours,

Aleen

**Comment by IonicaBizau** [comment]
That's pretty neat! ✨ 

I like how few of them have images as well. I was using the SVG urls from Shields, but if I'm not wrong, they only support text, right?

**Comment by aleen42** [comment]
Actually any data url of pictures including JPG, PNG, or SVG can be  used there. Due to the limitation of the URL, however, that will fail to generate, @IonicaBizau .

**Comment by IonicaBizau** [comment]
Hey @aleen42!

I'm going to update my badges and I've been thinking that I will maybe use some of these.
Also, I struggle creating one with the Amazon logo (https://image.flaticon.com/icons/png/512/2/2406.png)–saying *Buy me a book* or something similar.

Would be interesting to have a section with companies' logos (such as Amazon, PayPal, eBay etc).
If you added this (at least Amazon and PayPal), I'd be so thankful! :smile:

**Comment by aleen42** [comment]
@IonicaBizau No problems.

**Comment by IonicaBizau** [comment]
Maybe they can be in the `Inc.` section.

**Comment by IonicaBizau** [comment]
Maybe we can use FontAwesome:

 - https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/white/svg/amazon.svg
 - https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/white/svg/paypal.svg

**Comment by aleen42** [comment]
@IonicaBizau Okay, I am trying to make it more elegant.

**Comment by aleen42** [comment]
@IonicaBizau Check [the list of payment](https://github.com/aleen42/badges#payment), or do you mind help me to make this repository known more widely?

- ![](https://rawgit.com/aleen42/badges/master/src/amazon.svg)
- ![](https://rawgit.com/aleen42/badges/master/src/paypal.svg)

**Comment by IonicaBizau** [comment]
Awww, that's cute!

Patreon would be nice to have, as well: https://upload.wikimedia.org/wikipedia/commons/9/94/Patreon_logo.svg

**Comment by aleen42** [comment]
@IonicaBizau Check it, Patreon:

- ![patreon](https://rawgit.com/aleen42/badges/master/src/patreon.svg)

**Comment by IonicaBizau** [comment]
Thank you so much! I'm going to use these! :tada: :star2:

**Comment by aleen42** [comment]
@IonicaBizau You're welcome! 👍

**Comment by IonicaBizau** [comment]
I updated all my projects during the last night. Seems like it worked. :grin:

**Comment by aleen42** [comment]
@IonicaBizau If you have any new idea, just issue for it.
