### ISSUE TITLE
Update example in README

### ISSUE THREAD

**Issue by sievins** [aleen42/badges#10]
Just started using this CLI (awesome stuff btw 🎉). To get the color option to work I needed to provide the hex code without the `#` character. In the `README` the example uses the `#` character.

> badge -t Alipay -c "#1CACEB" -p alipay.svg -o output.svg

**Comment by aleen42** [comment]
I can't reproduce your situation, and can you give me a more detailed running script for testing?

```bash
$ badge -t Alipay -c "#1CACEB" -p alipay.svg -o output.svg
# success Create a badge for Alipay
```

**Comment by sievins** [comment]
Hey @aleen42. Sorry, I was supper unclear and didn't actually say what was broken.

The badge is created, but not with the color supplied by the `-c` option, instead it's black. By removing the hash symbol the badge is created with the correct color.

`badge -t Alipay -c "#008000" -p alipay.svg -o output.svg` creates a black badge.
`badge -t Alipay -c "008000" -p alipay.svg -o output.svg` creates a green badge.

Here's a gif of the issue. Hope that helps.

![badge-hash-issue](https://user-images.githubusercontent.com/8970298/113581602-3eff3f80-961f-11eb-917b-efa148b701ea.gif)

**Comment by aleen42** [comment]
@sievins The SVG file will generate the following snippet like this, and can you check your `not-green.svg`?

```js
<g clip-path="url(#a)">
    <path fill="#555" d="M0 0h25v20H0z"/>
    <path fill="#008000" d="M25 0h45v20H25z"/>
    <path fill="url(#b)" d="M0 0h70v20H0z"/>
</g>
```

After checking the logics, I find that it may be a problem around your Node, and can you specify your Node version? I have tested under Node 13.14.0 and cannot reproduce it.
