### ISSUE TITLE
add the Rollup badge

### ISSUE THREAD

**Issue by imjeen** [aleen42/badges#12]
[Rollup](https://rollupjs.org/) is a tool like Gulp, Webpack etc.
 
the SVG logo:  [https://rollupjs.org/logo.svg](https://rollupjs.org/logo.svg)

**Comment by aleen42** [comment]
@imjeen, feel free to reopen this issue when there is any suggestion.

![Rollup](https://badges.aleen42.com/src/rollup.svg)
