### ISSUE TITLE
slight differences in text-font to shields.io

### ISSUE THREAD

**Issue by Cube707** [aleen42/badges#15]
I just found that there are slight differences in the text-font of this badges and the ones comming directly from [shields.io](https://shield.io)(at least when using a icon from simpleicons.org and not sending svg-data), see here:

![from here](https://badges.aleen42.com/src/github.svg "from this project")
![shields.io badge](https://img.shields.io/static/v1?logo=github&label=&labelColor=gray&message=GitHub&color=%230D0D0D "from shield.io")

this can look a little off when mixing badges:
![from here](https://badges.aleen42.com/src/github.svg)![PyPI - Status](https://img.shields.io/pypi/status/readchar)

and could be improved:
![shields.io badge](https://img.shields.io/static/v1?logo=github&label=&labelColor=gray&message=GitHub&color=%230D0D0D)![PyPI - Status](https://img.shields.io/pypi/status/readchar)

This is a really miner issue, but I wanted to dokument it and maybe start a disscussion on it

**Comment by aleen42** [comment]
If you check the source of badges and sheilds.io, you will find that the implementation of shields.io is so wired that it scale it up to 110 and scale down to 0.1 again


```svg
<g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision"
   font-size="110">
    <image x="5" y="3" width="14" height="14" xlink:href="data:image/svg+xml;base64,xxx" />
    <text aria-hidden="true" x="465" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="370">GitHub</text>
    <text x="465" y="140" transform="scale(.1)" fill="#fff" textLength="370">GitHub</text>
</g>
```

And `badges` has used `12px` as its font size:

```svg
<g xmlns="http://www.w3.org/2000/svg" fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="12">
    <image x="5" y="3" width="14" height="14" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="data:image/svg+xml;base64,xxx"/>
    <text x="49.5" y="14.6" fill="#010101" fill-opacity=".3">GitHub</text>
    <text x="49.5" y="14">GitHub</text>
</g>
```

And I prefer to use `12px` because it is more ergonomic in most devices.

**Comment by Cube707** [comment]
Well thats strange 😂

Fair enough, like I said, its only a minor visual issue I just wanted to document. 

Feel free to keep it open or close it 👍

**Comment by aleen42** [comment]
Let me consider whether the repo should support different font size badges in the client tool, and accept `12px` as a standard in the README. Thanks for your feedback.

**Comment by aleen42** [comment]
1.2.1 relased!
