### ISSUE TITLE
Add Badge for Svelte

### ISSUE THREAD

**Issue by chessurisme** [aleen42/badges#17]
I think you miss Svelte, add one

**Comment by chessurisme** [comment]
Here's the SVG: https://upload.wikimedia.org/wikipedia/commons/1/1b/Svelte_Logo.svg

**Comment by aleen42** [comment]
![Svelte](https://badges.aleen42.com/src/svelte.svg) added, feel free to use it.

**Comment by chessurisme** [comment]
Thank you for your consideration!

**Comment by chessurisme** [comment]
Thank you for your consideration!

**Comment by chessurisme** [comment]
Thank you for your consideration!
