### ISSUE TITLE
How do you create such badges?

### ISSUE THREAD

**Issue by IonicaBizau** [aleen42/badges#2]
What's the process of using an SVG image in such badges? Would be useful for newcomers. :grin:

**Comment by aleen42** [comment]
Actually, I have used [shields](http://shields.io/) to create such badges. It's very simple, and this repository is mainly used to be a collection of advanced badges widely used in different projects.

If you want to create one, you may have to encode your SVG with base64, and then encode it with urlencode at the same time. 

With that value, passing it to the logo parameter of the following URI:

```https://img.shields.io/badge/-[NAME]-[COLOR VALUE].svg?logo=[BASE64_VALUE]```

As the length of URL has been limited, the value of encoded above has also been limited within some bytes, if you want to check how to create it with SVG, you can just check [the repository](https://github.com/badges/shields/).

**Comment by aleen42** [comment]
@IonicaBizau To work around the problem of long URL limitation, I will create another command line tool soon or later to make it more simple.

**Comment by IonicaBizau** [comment]
@aleen42 Nice! Are you resizing the images before converting them into base64?

PS. I sent you an email. :grin:

**Comment by aleen42** [comment]
@IonicaBizau According to the source code of shields, the width of the image is set manually, the value of which is 14 px by default.

**Comment by IonicaBizau** [comment]
@aleen42 So, does that mean you resized the images to 14x14 before encoding them in base64?

**Comment by aleen42** [comment]
@IonicaBizau Yup

**Comment by IonicaBizau** [comment]
Coolio! Thanks a lot! 🍰 

Maybe this should be documented in the readme file (so anybody can have the clear steps if they want to contribute).

**Comment by aleen42** [comment]
@IonicaBizau Command-line tool has been released and you can just install it by:

```bash
npm install -g badges-cli
```

If you need help after installation, you can just type:

```bash
badge -h
```

Or here is an example to create a badge as well:

```bash
badge -t Bitcoin -p ./bitcoin.svg -c F7931A -o output.svg
```

As it has been developed within just several hours, there should be bugs and enhancements to improve.

**Comment by IonicaBizau** [comment]
Cool! :+1: That's amazing!!!!
