### ISSUE TITLE
Add Bitcoin

### ISSUE THREAD

**Issue by IonicaBizau** [aleen42/badges#3]
Adding Bitcoint would be handy too! :grin:

**Comment by aleen42** [comment]
@IonicaBizau Is there any official supported SVG file for Bitcoint?

**Comment by IonicaBizau** [comment]
Maybe this: https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg

**Comment by aleen42** [comment]
@IonicaBizau Check it:

![bitcoin](https://rawgit.com/aleen42/badges/master/src/bitcoin.svg)

**Comment by IonicaBizau** [comment]
Beautiful! 👍 Thanks a lot!
