### ISSUE TITLE
Style option for flat badge production?

### ISSUE THREAD

**Issue by ghost** [aleen42/badges#7]
I use the flat square badge pretty religiously in my repositories. Any plans to add styles support for different badge types in the future?

**Comment by aleen42** [comment]
@jhabdas , I don't really understand how to add style supports, do you mind giving me an exact example?

**Comment by ghost** [comment]
Absolutely. I apologize for the oversight. Here's an example of the flat square I use in one of my public repos:

<a href="https://cdn.jsdelivr.net/npm/fetch-inject">
<img src="http://img.badgesize.io/https://cdn.jsdelivr.net/npm/fetch-inject?compression=gzip&style=flat-square" alt="Compressed size of UMD bundle"></a>

**Comment by aleen42** [comment]
@jhabdas I am sorry to tell that it's not the purpose of my project, and if you want to create yourself a badge like this, check the project, [shields.io](https://github.com/badges/shields/blob/master/README.md). My purpose of creating this project is to collect a list of flat badges for different qute brands. 😄

**Comment by ghost** [comment]
For what it's worth your project is better than Shields but you need to extend it if you want to see the stargazers

**Comment by jhabdas** [comment]
> My purpose of creating this project is to collect a list of flat badges for different qute brands

And I hear you're taking my example to literally; please open your mind to branding with a flat badge, assuming it's not breaking any copyright law.

**Comment by aleen42** [comment]
@jhabdas Thanks for your suggestions, and I will take it in consideration soon or later, of course branding with a flat square style is also awesome alternative. As it's a little busy about completing one of my project, named [geometries](https://github.com/aleen42/geometries), this should be planned later after I have done my another job. Thanks for your reply again.

**Comment by ghost** [comment]
I agree, and thank you for your understanding.

**Comment by aleen42** [comment]
@ghost Sorry for a late release, and check the README here for style option: https://github.com/aleen42/badges/blob/master/README_flat_square.md
