### ISSUE TITLE
badge for vanilla JS

### ISSUE THREAD

**Issue by hozefaj** [aleen42/badges#8]
would be good to have a badge for vanilla JS here since there are badges for popular libraries/frameworks.

Something thats here: http://constructs.stampede-design.com/wp-content/uploads/2014/10/javascript.jpg

**Comment by aleen42** [comment]
Is there any vector graph for it?

**Comment by aleen42** [comment]
@hozefaj I have created one for this issue, check the following:

[![plainjs](https://rawgit.com/aleen42/badges/master/src/plainjs.svg)](https://cdn.rawgit.com/aleen42/badges/master/src/plainjs.svg)

**Comment by hozefaj** [comment]
Looks good. Maybe we don't need the word 'Vanilla'. Just having JavaScript should be enough. Thanks.

**Comment by aleen42** [comment]
The following should be awesome:

![javascript](https://rawgit.com/aleen42/badges/master/src/javascript.svg)

**Comment by hozefaj** [comment]
Yes indeed. Awesome. Thanks

**Comment by aleen42** [comment]
Hah, just use it.
