### ISSUE TITLE
Improve contrast of text color

### ISSUE THREAD

**Issue by Krinkle** [aleen42/badges#9]
For some badges, the background color is very bright which makes the text (currently white) difficult to read.

Especially the yellow ones like for Vanilla JavaScript, Coremail Lunkr, Real Madrid, and Dreamweaver.

* ![](https://raw.githubusercontent.com/aleen42/badges/1.1.9/src/javascript.svg)
* ![](https://raw.githubusercontent.com/aleen42/badges/1.1.9/src/lunkr.svg)
* ![](https://raw.githubusercontent.com/aleen42/badges/1.1.9/src/real_madrid.svg)
* ![](https://raw.githubusercontent.com/aleen42/badges/1.1.9/src/dreamweaver.svg)

Perhaps for these, the text color could be black?

**Comment by aleen42** [comment]
Do you accept like this:

- ![](https://aleen42.github.io/badges/src/javascript_dfc.svg)
- ![](https://aleen42.github.io/badges/src/dreamweaver_dfc.svg)

**Comment by Krinkle** [comment]
Yes!

**Comment by aleen42** [comment]
Check the list of [here](https://github.com/aleen42/badges/blob/master/README_dfc.md)
